# Etapa de construcción
FROM node:20.9.0 AS build
# Establece el directorio de trabajo
WORKDIR /app
# Copia los archivos del proyecto
COPY . .
# Instala las dependencias
RUN npm install --force
# Construye la aplicación Angular
RUN npm run build --prod
# Etapa de producción
FROM nginx:stable-alpine
# Copia los archivos construidos al directorio de Nginx
COPY --from=build /app/dist/strattonapp-front /usr/share/nginx/html

# Expone el puerto 80
EXPOSE 80
# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
