# Etapa de construcción
FROM maven:3-openjdk-17 as builder

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos del proyecto
COPY pom.xml .
COPY src ./src

# Construye el paquete de la aplicación
RUN mvn clean package -DskipTests

# Etapa de producción
FROM openjdk:17-alpine

# Variables de entorno
ENV BBDD_HOST="db"
ENV BBDD_NAME="strattonapp"
ENV APP_PORT=8080
ENV LOG_LEVEL="INFO"
ENV DLL_AUTO="update"

# Volumen para datos temporales y archivos multimedia
VOLUME /tmp
VOLUME /mediafiles

# Puerto expuesto
EXPOSE 8080

# Copia el archivo JAR construido de la etapa de construcción
COPY --from=builder /usr/src/app/target/Backend-0.0.1-SNAPSHOT.jar /app/app.jar

# Comando de inicio
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
