# Etapa de construcción
FROM maven:3-openjdk-17 as builder
COPY pom.xml /usr/src/app/
COPY src /usr/src/app/src
RUN mvn -f /usr/src/app/pom.xml clean package -DskipTests

# Etapa de producción
FROM openjdk:17-alpine

# Variables de entorno
ENV BBDD_HOST="db"
ENV BBDD_NAME="strattonapp"
ENV APP_PORT=8080
ENV LOG_LEVEL="INFO"
ENV DLL_AUTO="update"

# Volumen para datos temporales y archivos multimedia
VOLUME /tmp
VOLUME /mediafiles

# Puerto expuesto
EXPOSE 8080

# Copiar el archivo JAR construido de la etapa de construcción
COPY --from=builder /usr/src/app/target/StrattonApp-Backend-0.0.1-SNAPSHOT.jar /app/app.jar

# Comando de inicio
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
