insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (1, 41018, 'Masty', 'Sevilla', 1);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (2, 39017, 'Nacka', 'Málaga', 2);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (3, 33854, 'Dzyarzhynsk', 'Cádiz', 3);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (4, 41020, 'Dongzhou', 'Jaen', 4);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (5, 57102, 'Jefferson City', 'Granada', 5);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (6, 69104, 'Tonglin', 'Córdoba', 6);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (7, 41018, 'Opatów', 'Almería', 7);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (8, 39017, 'Eauripik', 'Huelva', 8);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (9, 33854, 'Bludov', 'Sevilla', 9);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (10, 41020, 'Linjiang', 'Málaga', 10);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (11, 57102, 'Beverwijk', 'Cádiz', 11);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (12, 69104, 'Krajan Bakalan', 'Jaen', 12);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (13, 41018, 'Shaxi', 'Granada', 13);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (14, 39017, 'Banggel', 'Córdoba', 14);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (15, 33854, 'Catujal Velho', 'Almería', 15);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (16, 41020, 'Atalaia', 'Huelva', 16);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (17, 57102, 'Jaroměř', 'Sevilla', 17);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (18, 69104, 'Cibunar', 'Málaga', 18);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (19, 41018, 'Jiuheyuan', 'Cádiz', 19);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (20, 39017, 'Bagusan', 'Jaen', 20);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (21, 33854, 'Rizómata', 'Granada', 21);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (22, 41020, 'Halteu', 'Córdoba', 22);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (23, 57102, 'Verkhniy Avzyan', 'Almería', 23);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (24, 69104, 'Zarqa', 'Huelva', 24);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (25, 41018, 'Palon', 'Sevilla', 25);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (26, 39017, 'San Pedro del Paraná', 'Málaga', 26);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (27, 33854, 'Fargo', 'Cádiz', 27);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (28, 41020, 'Liangshan', 'Jaen', 28);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (29, 57102, 'Värmdö', 'Granada', 29);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (30, 69104, 'Bifeng', 'Córdoba', 30);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (31, 41018, 'Philadelphia', 'Almería', 31);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (32, 39017, 'Eloúnda', 'Huelva', 32);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (33, 33854, 'Chuncheon', 'Sevilla', 33);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (34, 41020, 'Juuka', 'Málaga', 34);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (35, 57102, 'Batulawang', 'Cádiz', 35);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (36, 69104, 'Kasongo', 'Jaen', 36);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (37, 41018, 'Tanggung', 'Granada', 37);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (38, 39017, 'Zhangting', 'Córdoba', 38);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (39, 33854, 'Saint-Jérôme', 'Almería', 39);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (40, 41020, 'Sidonganti', 'Huelva', 40);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (41, 57102, 'Panikihan', 'Sevilla', 41);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (42, 69104, 'Konga', 'Málaga', 42);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (43, 41018, 'Židlochovice', 'Cádiz', 43);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (44, 39017, 'Saransk', 'Jaen', 44);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (45, 33854, 'Ferkessédougou', 'Granada', 45);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (46, 41020, 'Oenunu', 'Córdoba', 46);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (47, 57102, 'Mérignac', 'Almería', 47);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (48, 69104, 'Marseille', 'Huelva', 48);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (49, 41018, 'Kufa', 'Sevilla', 49);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (50, 39017, 'Dubinino', 'Málaga', 50);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (51, 33854, 'Krajan Dermawuharjo', 'Cádiz', 51);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (52, 41020, 'Staré Křečany', 'Jaen', 52);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (53, 57102, 'Ilek', 'Granada', 53);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (54, 69104, 'La Falda', 'Córdoba', 54);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (55, 41018, 'Maogang', 'Almería', 55);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (56, 39017, 'Stockholm', 'Huelva', 56);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (57, 33854, 'Tetaf', 'Sevilla', 57);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (58, 41020, 'Mamurras', 'Málaga', 58);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (59, 57102, 'Tabouda', 'Cádiz', 59);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (60, 69104, 'Podkamennaya Tunguska', 'Jaen', 60);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (61, 41018, 'Chŏngju', 'Granada', 61);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (62, 39017, 'Mahuta', 'Córdoba', 62);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (63, 33854, 'Kedungtuban', 'Almería', 63);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (64, 41020, '‘Aqrah', 'Huelva', 64);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (65, 57102, 'Ettelbruck', 'Sevilla', 65);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (66, 69104, 'Großklein', 'Málaga', 66);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (67, 41018, 'Sumalig', 'Cádiz', 67);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (68, 39017, 'Xixiang', 'Jaen', 68);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (69, 33854, 'Almere Stad', 'Granada', 69);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (70, 41020, 'Al Bīrah', 'Córdoba', 70);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (71, 57102, 'Aghada', 'Almería', 71);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (72, 69104, 'Qiaobian', 'Huelva', 72);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (73, 41018, 'Dadu', 'Sevilla', 73);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (74, 39017, 'Mekkaw', 'Málaga', 74);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (75, 33854, 'Thị Trấn Thọ Xuân', 'Cádiz', 75);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (76, 41020, 'Eiguliai', 'Jaen', 76);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (77, 57102, 'Saint-Fargeau-Ponthierry', 'Granada', 77);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (78, 69104, 'Silvino Lobos', 'Córdoba', 78);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (79, 41018, 'Ujmisht', 'Almería', 79);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (80, 39017, 'Jialu', 'Huelva', 80);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (81, 33854, 'Reggada', 'Sevilla', 81);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (82, 41020, 'Old Kilcullen', 'Málaga', 82);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (83, 57102, 'Xitou', 'Cádiz', 83);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (84, 69104, 'Ensanche Luperón', 'Jaen', 84);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (85, 41018, 'Padangbai', 'Granada', 85);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (86, 39017, 'La Fortuna', 'Córdoba', 86);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (87, 33854, 'Kumla', 'Almería', 87);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (88, 41020, 'San Isidro', 'Huelva', 88);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (89, 57102, 'Aku', 'Sevilla', 89);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (90, 69104, 'Daweishan', 'Málaga', 90);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (91, 41018, 'Rongcheng', 'Cádiz', 91);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (92, 39017, 'Emiliano Zapata', 'Jaen', 92);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (93, 33854, 'Sitiarjo', 'Granada', 93);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (94, 41020, 'Goya', 'Córdoba', 94);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (95, 57102, 'Shengli', 'Almería', 95);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (96, 69104, 'Kaulon', 'Huelva', 96);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (97, 41018, 'Hita', 'Sevilla', 97);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (98, 39017, 'Tobatí', 'Málaga', 98);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (99, 33854, 'Sopla', 'Cádiz', 99);
insert into UBICACION (idUbicacion, ZIP, municipio, Ciudad, idCliente) values (100, 41020, 'Santa Bárbara', 'Jaen', 100);
